import pptx
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pathlib import Path
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

# Ensure output directory exists
out_dir = Path("sih_presentation")
out_dir.mkdir(parents=True, exist_ok=True)

src_ppt = Path("PPT - SatSense .pptx")
if not src_ppt.exists():
    print(f"Error: {src_ppt} not found.")
    sys.exit(1)

prs = pptx.Presentation(str(src_ppt))
print(f"Loaded {src_ppt.name} with {len(prs.slides)} slides.")

# ==============================================================================
# SLIDE 1: Title Slide Polish
# ==============================================================================
slide1 = prs.slides[0]
# Add a punchy subtitle box if not present
sub_box = slide1.shapes.add_textbox(Inches(0.67), Inches(4.7), Inches(7.5), Inches(0.8))
tf1 = sub_box.text_frame
tf1.word_wrap = True
p1 = tf1.paragraphs[0]
p1.text = "Physics-Grounded, Hallucination-Free Multimodal Remote Sensing Assistant with Deterministic GIS Verification"
p1.font.size = Pt(13)
p1.font.bold = True
p1.font.color.rgb = RGBColor(0x0A, 0x36, 0x63) # Deep ISRO Blue

# ==============================================================================
# SLIDE 2: Problem & Solution Refinement
# ==============================================================================
slide2 = prs.slides[1]

# Shape 9 is PROBLEM HOOK text
s2_hook = slide2.shapes[9]
tf2_hook = s2_hook.text_frame
tf2_hook.word_wrap = True
tf2_hook.clear()

p = tf2_hook.paragraphs[0]
p.text = "\"During Assam's monsoon floods, NDRF coordinators can't get a fast, trustworthy answer to 'how much land is underwater?' Regular AI models can't read satellite coordinates or calculate real ground area — and manual assessment takes ~4 hours, with monsoon clouds blocking optical satellites roughly 78% of the time.\""
p.font.size = Pt(9.5)

p_kw = tf2_hook.add_paragraph()
p_kw.text = "• Scope In: Sentinel-1/RISAT SAR, Sentinel-2/Cartosat Optical, DEM slope gating, OGC GeoJSON, Offline Field Packs.\n• Scope Out: Uncalibrated video, streaming drone feeds, black-box LLM area guesses."
p_kw.font.size = Pt(8.5)
p_kw.font.bold = True
p_kw.font.color.rgb = RGBColor(0x1B, 0x4D, 0x3E) # Dark Forest Green

# Shape 11 is CORE PHILOSOPHY
s2_philo = slide2.shapes[11]
tf2_philo = s2_philo.text_frame
tf2_philo.clear()
p = tf2_philo.paragraphs[0]
p.text = "Understand → Check → Choose → Analyze → Verify → Explain"
p.font.size = Pt(11)
p.font.bold = True
p.font.color.rgb = RGBColor(0x0A, 0x36, 0x63)

p2 = tf2_philo.add_paragraph()
p2.text = "SatQuery AI acts as a \"Careful Coordinator\" rather than a black-box chatbot. It validates coordinate integrity before it analyzes, and triggers an Honest Refusal rather than guessing."
p2.font.size = Pt(9.5)

# Shape 7 is PROPOSED SOLUTION
s2_sol = slide2.shapes[7]
tf2_sol = s2_sol.text_frame
tf2_sol.clear()

sol_items = [
    ("All-Weather Satellite Fusion", "Fuses Cartosat-2S / Sentinel-2 optical with RISAT-1A / Sentinel-1 C-band SAR; radar microwaves penetrate 100% of dense monsoon clouds, day or night."),
    ("Deterministic Area Guard", "Area (km²) = (N_pixels × GSD_x × GSD_y) / 1,000,000, computed directly from GeoTIFF affine transform metadata — never generated by LLM text tokens."),
    ("Honest Refusal Engine", "If CRS mismatch, <80% spatial overlap (IoU), or >80% cloud cover without a SAR pair, the system halts safely and explains the exact scientific reason."),
    ("Visual Proof & Vectors", "Every answer ships with an interactive cross-modal Agreement/Disagreement map and certified RFC 7946 GeoJSON export for QGIS / Bhuvan.")
]

for title, body in sol_items:
    p_t = tf2_sol.add_paragraph() if tf2_sol.paragraphs[0].text else tf2_sol.paragraphs[0]
    p_t.text = f"{title} — "
    p_t.font.bold = True
    p_t.font.size = Pt(9.5)
    p_t.font.color.rgb = RGBColor(0x0A, 0x36, 0x63)
    
    # Add body run
    run = p_t.add_run()
    run.text = body
    run.font.bold = False
    run.font.size = Pt(9.0)
    run.font.color.rgb = RGBColor(0x22, 0x22, 0x22)

# Shape 5 is INNOVATION & UNIQUENESS
s2_innov = slide2.shapes[5]
tf2_innov = s2_innov.text_frame
tf2_innov.clear()

innov_items = [
    ("Elevation-Gated Radar", "Incorporates SRTM/CartoDEM slope & aspect checks to eliminate mountain shadow false alarms and hill-slope water misclassifications."),
    ("Actionable Disagreement Maps", "Pixel-wise cross-modal comparator that highlights exactly where optical and radar evidence conflict under partial cloud cover."),
    ("Deterministic Math Contract", "Zero generative AI hallucination on physical quantities: flood perimeters, water areas, and NDVI vegetation indices are computed by deterministic C-libraries."),
    ("Offline Tactical Field Packs", "Packages georeferenced summary maps, vector layers, and intelligence PDF dossiers (<10 MB) deployable to field responders with zero internet.")
]

for title, body in innov_items:
    p_t = tf2_innov.add_paragraph() if tf2_innov.paragraphs[0].text else tf2_innov.paragraphs[0]
    p_t.text = f"{title} — "
    p_t.font.bold = True
    p_t.font.size = Pt(9.5)
    p_t.font.color.rgb = RGBColor(0xB2, 0x47, 0x00) # Deep Terracotta / Orange
    
    run = p_t.add_run()
    run.text = body
    run.font.bold = False
    run.font.size = Pt(9.0)
    run.font.color.rgb = RGBColor(0x22, 0x22, 0x22)

# ==============================================================================
# SLIDE 4: Feasibility & Viability Grounding
# ==============================================================================
slide4 = prs.slides[3]

# Shape 2 is FEASIBILITY
s4_feas = slide4.shapes[2]
tf4_feas = s4_feas.text_frame
tf4_feas.clear()

feas_items = [
    ("Built on Open-Source Tooling", "Leverages standard FOSS libraries (FastAPI, Rasterio, GDAL, PyTorch, Pydantic) with zero costly runtime licensing fees."),
    ("Open Geospatial Data Feeds", "Directly ingests free satellite streams: ISRO Bhuvan GeoAI, Copernicus SciHub (Sentinel-1/2), USGS EarthExplorer, and NASA Earthdata."),
    ("Compute & Architecture Feasibility", "Zero-GPU emergency CPU fallback ensures core disaster analysis runs on standard laptops; scale-out GPU bursts handle heavy VLM reasoning. Validated on calibrated BigEarthNet S1/S2 pairs with <1% geocoding affine error.")
]

for title, body in feas_items:
    p_t = tf4_feas.add_paragraph() if tf4_feas.paragraphs[0].text else tf4_feas.paragraphs[0]
    p_t.text = f"{title} — "
    p_t.font.bold = True
    p_t.font.size = Pt(9.5)
    p_t.font.color.rgb = RGBColor(0x0A, 0x36, 0x63)
    
    run = p_t.add_run()
    run.text = body
    run.font.bold = False
    run.font.size = Pt(9.0)

# Shape 7 is VIABILITY
s4_viab = slide4.shapes[7]
tf4_viab = s4_viab.text_frame
tf4_viab.clear()

viab_items = [
    ("TCO & Economic Savings", "Saves ₹15–20 Lakhs/year in proprietary GIS software licenses (ArcGIS Server) through pure FOSS architecture."),
    ("Air-Gapped Defense Readiness", "Containerized Docker architecture deployable fully offline on-premise, guaranteeing sensitive ISRO/defence imagery never leaves sovereign borders."),
    ("Operational Scalability", "Pre-tested modular adapters allow instant expansion from flood inundation to cyclone damage, forest fires, and urban encroachment."),
    ("Field-Tested Workflow", "Generates lightweight mobile-ready field packs (<10 MB) providing NDRF teams with offline interactive GeoJSON vectors.")
]

for title, body in viab_items:
    p_t = tf4_viab.add_paragraph() if tf4_viab.paragraphs[0].text else tf4_viab.paragraphs[0]
    p_t.text = f"{title} — "
    p_t.font.bold = True
    p_t.font.size = Pt(9.5)
    p_t.font.color.rgb = RGBColor(0x1B, 0x4D, 0x3E)
    
    run = p_t.add_run()
    run.text = body
    run.font.bold = False
    run.font.size = Pt(9.0)

# ==============================================================================
# SLIDE 6: COMPLETE REDESIGN — Strategic Roadmap, References & Decision
# ==============================================================================
slide6 = prs.slides[5]

# Update Title to show Roadmap & Strategic Impact
s6_title = slide6.shapes[1]
s6_title.text_frame.text = "STRATEGIC ROADMAP, RESEARCH & NATIONAL IMPACT"
s6_title.text_frame.paragraphs[0].font.size = Pt(20)
s6_title.text_frame.paragraphs[0].font.bold = True
s6_title.text_frame.paragraphs[0].font.color.rgb = RGBColor(0x0A, 0x36, 0x63)

# Clear old link boxes and arrow pentagons from shape 4 to 18
for idx in [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23, 24, 25, 26, 27]:
    if idx < len(slide6.shapes):
        s = slide6.shapes[idx]
        if s.has_text_frame:
            s.text_frame.clear()
        # Set transparent or zero dimensions if needed

# Repurpose Shape 19 & 20 (Left Box) into: STRATEGIC ROADMAP (NOW -> NEXT -> THEN -> FUTURE)
s6_rm_hdr = slide6.shapes[20] # Header
s6_rm_hdr.left = Inches(0.67)
s6_rm_hdr.top = Inches(1.35)
s6_rm_hdr.width = Inches(5.8)
s6_rm_hdr.height = Inches(0.5)
s6_rm_hdr.text_frame.text = "Strategic Roadmap (NOW → NEXT → THEN → FUTURE)"
s6_rm_hdr.text_frame.paragraphs[0].font.size = Pt(11)
s6_rm_hdr.text_frame.paragraphs[0].font.bold = True

s6_rm_body = slide6.shapes[19] # Body
s6_rm_body.left = Inches(0.67)
s6_rm_body.top = Inches(1.85)
s6_rm_body.width = Inches(5.8)
s6_rm_body.height = Inches(4.9)
tf6_rm = s6_rm_body.text_frame
tf6_rm.clear()

roadmap_items = [
    ("NOW (SIH Working Prototype)", "• Deterministic SAR (Lee filter + Otsu) & Optical (NDVI/NDWI) engines.\n• 6-Step verification pipeline with typed Pydantic v2 Query Contracts.\n• Offline Tactical Field Pack generator (<10 MB GeoJSON + PDF).\n• 99 automated test cases passing with zero regressions."),
    ("NEXT (3–6 Months / Pilot)", "• Native integration with ISRO Bhuvan STAC API & MOSDAC data portals.\n• District-level pilot deployment with Assam (ASDMA) & Odisha (OSDMA).\n• Automatic CartoDEM / SRTM slope-shadow correction pipeline."),
    ("THEN (1 Year / Scaling)", "• Dual-frequency L+S band support for upcoming NASA-ISRO SAR (NISAR).\n• Containerized edge deployment on NDRF mobile tactical command trucks.\n• Multi-temporal 3D flood depth and subsidence tracking."),
    ("FUTURE (National Ecosystem)", "• Pan-India National Automated Disaster Intelligence Engine (NADIE).\n• Real-time multi-hazard response (cyclone, landslide, forest fire, drought).")
]

for phase, desc in roadmap_items:
    p_h = tf6_rm.add_paragraph() if tf6_rm.paragraphs[0].text else tf6_rm.paragraphs[0]
    p_h.text = phase
    p_h.font.bold = True
    p_h.font.size = Pt(9.5)
    p_h.font.color.rgb = RGBColor(0x0A, 0x36, 0x63)
    
    p_d = tf6_rm.add_paragraph()
    p_d.text = desc
    p_d.font.size = Pt(8.5)
    p_d.font.color.rgb = RGBColor(0x22, 0x22, 0x22)

# Repurpose Shape 21 & 22 (Right Box) into: RESEARCH EVIDENCE, STANDARDS & JURY DECISION
s6_ev_hdr = slide6.shapes[22] # Header
s6_ev_hdr.left = Inches(6.8)
s6_ev_hdr.top = Inches(1.35)
s6_ev_hdr.width = Inches(5.8)
s6_ev_hdr.height = Inches(0.5)
s6_ev_hdr.text_frame.text = "Research Foundations, Standards & Academic Rigor"
s6_ev_hdr.text_frame.paragraphs[0].font.size = Pt(11)
s6_ev_hdr.text_frame.paragraphs[0].font.bold = True

s6_ev_body = slide6.shapes[21] # Body
s6_ev_body.left = Inches(6.8)
s6_ev_body.top = Inches(1.85)
s6_ev_body.width = Inches(5.8)
s6_ev_body.height = Inches(4.9)
tf6_ev = s6_ev_body.text_frame
tf6_ev.clear()

ev_items = [
    ("Foundational Remote Sensing Literature", "• BigEarthNet.txt (Herzog et al., arXiv:2603.29630, 2026) — 9.55M multimodal pairs.\n• GeoChat 7B (Kuckreja et al., CVPR 2024) — Grounded RS vision-language reasoning.\n• EarthGPT (Zhang et al., IEEE TGRS 2024) — Multi-sensor remote sensing AI.\n• CDVQA (Yuan et al., IEEE TGRS 2022) — Change detection visual QA."),
    ("National Portals & Geospatial Standards", "• Government Portals: ISRO Bhuvan GeoAI, SAC MOSDAC, NDMA.\n• Open Standards: OGC STAC API v1.0, RFC 7946 GeoJSON, WGS84 (EPSG:4326).\n• Satellite Data Repositories: ESA Copernicus SciHub, USGS EarthExplorer, NASA."),
    ("Engineering Defense Guarantee", "• Zero AI hallucination on physical areas (calculated strictly via Affine matrix).\n• SAR backscatter processed in linear power domain (dB arithmetic strictly guarded).\n• 100% reproducible test suite with zero synthetic data pollution in production."),
    ("Closing Value Statement / Jury Ask", "\"SatQuery AI bridges the critical gap between raw ISRO space pixels and instant, lifesaving field decisions. Scientifically defensible, reproducible, and ready for deployment.\"")
]

for sec, desc in ev_items:
    p_h = tf6_ev.add_paragraph() if tf6_ev.paragraphs[0].text else tf6_ev.paragraphs[0]
    p_h.text = sec
    p_h.font.bold = True
    p_h.font.size = Pt(9.5)
    p_h.font.color.rgb = RGBColor(0xB2, 0x47, 0x00) if "Closing" in sec else RGBColor(0x0A, 0x36, 0x63)
    
    p_d = tf6_ev.add_paragraph()
    p_d.text = desc
    p_d.font.size = Pt(8.5)
    p_d.font.color.rgb = RGBColor(0x0A, 0x36, 0x63) if "Closing" in sec else RGBColor(0x22, 0x22, 0x22)
    if "Closing" in sec:
        p_d.font.bold = True

# Save updated PPT
target_ppt = out_dir / "SatQuery_AI_SIH2026_SatSense_V2.pptx"
prs.save(str(target_ppt))
print(f"[SUCCESS] Enhanced presentation saved to: {target_ppt}")
